export const GET_OFFRES_DETAILES = "GET_OFFRES_DETAILES";
export const GET_OFFRES_DETAILES_SUCCESS = "GET_OFFRES_DETAILES_SUCCESS";
export const GET_CREDIT_TYPE="GET_CREDIT_TYPE";
export const GET_CREDIT_TYPE_SUCESS="GET_CREDIT_TYPE_SUCESS"

