export const GET_PROFILE_DETAILES = "GET_PROFILE_DETAILES";
export const GET_PROFILE_DETAILES_SUCCESS = "GET_PROFILE_DETAILES_SUCCESS";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const PROFILE_MODIFIED_FALSE = "PROFILE_MODIFIED_FALSE";
export const DELETE_PROFILE = "DELETE_PROFILE";
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS";
